site_name: 资产管理系统文档

nav:
  - OKOK: index.md
  - 项目简介: intro.md
  - 模块设计: modules.md
  - API文档: api.md
  - 数据库模型: database.md
  - 技术选型和部署: tech.md
  - 测试文档: test.md
  - 用户使用指南: user-guide.md

theme:
  name: material
